!       2DFCANTASK Error code facility definition file.
!
! Description:
!       Error code defintions for the 2DFCANTASK sub-system.
!
! Support: {function author}, AAO
!
! History:
!     02-Mar-2018 - KS - Original version
!    
!
! "@(#) $Id: ACMM:2dFCanTask/2dFCanTask_err.msg,v 1.4 29-Mar-2018 20:38:38+10 ks $"
!
.TITLE   2DFCANTASK_ERR  template DRAMA Task 
.FACILITY TDFCANTASK,1092/PREFIX=TDFCANTASK__
.SEVERITY ERROR
.BASE 2
MALLOCERR "Malloc error"
NOTINIT "The task has not been initialised"
.END
