!       2DFCANTASK Error code facility definition file.
!
! Description:
!       Error code defintions for the 2DFCANTASK sub-system.
!
! Support: {function author}, AAO
!
! History:
!     02-Mar-2018 - KS - Original version
!    
!
! "@(#) $Id: ACMM:2dFCanTask/2dfcantask_err.msg,v 1.0 02-Mar-2018 13:28:55+11 ks $"
!
.TITLE   2DFCANTASK_ERR  template DRAMA Task 
.FACILITY 2DFCANTASK,1092/PREFIX=2DFCANTASK__
.SEVERITY ERROR
.BASE 2
MALLOCERR "Malloc error"
NOTINIT "The task has not been initialised"
.END
