#ifndef TDFGRIPPERTASK_ERRH
#define TDFGRIPPERTASK_ERRH 1
/* C language ERROR include file
 * Generated by /instsoft/drama/release/messgen/r2.4-104-g7640bdb/linux_x86_64/messgen utility
 * from input file TdFGripperTask_err.msg at Mon Jun  2 14:46:38 2025
 */

/* Facility number */
#define TDFGRIPPERTASK__FACNUM 1092

/* OK Status symbol */
#define TDFGRIPPERTASK__OK 0

/* Raised an error when setting up the amps */
#define TDFGRIPPERTASK__AMP_ERR 0xC448012

/* CAMERA raised an error */
#define TDFGRIPPERTASK__CAMERA 0xC44801A

/* Button is in the jaw */
#define TDFGRIPPERTASK__BUTT_IN_JAWS 0xC448022

/* Malloc error */
#define TDFGRIPPERTASK__MALLOCERR 0xC44802A

/* The gantry failed to move to the target position */
#define TDFGRIPPERTASK__NO_GANTRY_MOVEMENT 0xC448032

/* The task has not been initialised */
#define TDFGRIPPERTASK__NOTINIT 0xC44803A

/* No arguments are provided */
#define TDFGRIPPERTASK__NO_ARGUMENTS 0xC448042

/* The environment variable used to find the parameter files is not defined */
#define TDFGRIPPERTASK__NO_ENV_VAR 0xC44804A

/* Fibre-end not in field of view */
#define TDFGRIPPERTASK__NO_FIBRE 0xC448052

/* Fiducial not in field of view */
#define TDFGRIPPERTASK__NO_FID 0xC44805A

/* No image is taken by the camera */
#define TDFGRIPPERTASK__NO_IMAGE 0xC448062

/* The move is not safe */
#define TDFGRIPPERTASK__NOT_SAFEMOVE 0xC44806A

/* Gantry is not parked */
#define TDFGRIPPERTASK__NOT_PARKED 0xC448072

/* No button is being carried */
#define TDFGRIPPERTASK__NO_BUTTON 0xC44807A

/* The task is taking other actions */
#define TDFGRIPPERTASK__IN_USE 0xC448082

/* Insufficent fids found to do a survey calculation */
#define TDFGRIPPERTASK__INSUF_FIDS 0xC44808A

/* Invalid centroiding window definition */
#define TDFGRIPPERTASK__INVWIN 0xC448092

/* The pick up position is invalid */
#define TDFGRIPPERTASK__INV_PICK_POS 0xC44809A

/* Invalid input arguments */
#define TDFGRIPPERTASK__INV_INPUT_ARGUMENT 0xC4480A2

/* Invalid centroid value */
#define TDFGRIPPERTASK__INV_CENTROID 0xC4480AA

/* Invalid target gantry position */
#define TDFGRIPPERTASK__INV_POS 0xC4480B2

/* Gantry is parked */
#define TDFGRIPPERTASK__PARKED 0xC4480BA

/* raised an error when running a subtask */
#define TDFGRIPPERTASK__PROG_ERROR 0xC4480C2

/* Check the SDS file, some fields are missing */
#define TDFGRIPPERTASK__READ_ERROR 0xC4480CA

/* Action not possible as we are in simulation mode */
#define TDFGRIPPERTASK__SIMULATION 0xC4480D2

/* Error returned by slalib function */
#define TDFGRIPPERTASK__SLALIB 0xC4480DA

/* Error occured during search action */
#define TDFGRIPPERTASK__SEARCH 0xC4480E2

/* The height of Z axis is not correct */
#define TDFGRIPPERTASK__WRONG_HEIGHT 0xC4480EA

#endif
