#ifndef TDFGRIPPERTASK_ERR_MSGTH
#define TDFGRIPPERTASK_ERR_MSGTH 1
/*  Message table include file
 *  Generated by /instsoft/drama/release/messgen/r2.4-104-g7640bdb/linux_x86_64/messgen utility
 *  from input file TdFGripperTask_err.msg at Mon Jun  2 14:46:38 2025
  */
static MessTabType MessFacTab_TDFGRIPPERTASK[] = {
    { 2, "AMP_ERR", 
        "Raised an error when setting up the amps" },
    { 3, "CAMERA", 
        "CAMERA raised an error" },
    { 4, "BUTT_IN_JAWS", 
        "Button is in the jaw" },
    { 5, "MALLOCERR", 
        "Malloc error" },
    { 6, "NO_GANTRY_MOVEMENT", 
        "The gantry failed to move to the target position" },
    { 7, "NOTINIT", 
        "The task has not been initialised" },
    { 8, "NO_ARGUMENTS", 
        "No arguments are provided" },
    { 9, "NO_ENV_VAR", 
        "The environment variable used to find the parameter files is not defined" },
    { 10, "NO_FIBRE", 
        "Fibre-end not in field of view" },
    { 11, "NO_FID", 
        "Fiducial not in field of view" },
    { 12, "NO_IMAGE", 
        "No image is taken by the camera" },
    { 13, "NOT_SAFEMOVE", 
        "The move is not safe" },
    { 14, "NOT_PARKED", 
        "Gantry is not parked" },
    { 15, "NO_BUTTON", 
        "No button is being carried" },
    { 16, "IN_USE", 
        "The task is taking other actions" },
    { 17, "INSUF_FIDS", 
        "Insufficent fids found to do a survey calculation" },
    { 18, "INVWIN", 
        "Invalid centroiding window definition" },
    { 19, "INV_PICK_POS", 
        "The pick up position is invalid" },
    { 20, "INV_INPUT_ARGUMENT", 
        "Invalid input arguments" },
    { 21, "INV_CENTROID", 
        "Invalid centroid value" },
    { 22, "INV_POS", 
        "Invalid target gantry position" },
    { 23, "PARKED", 
        "Gantry is parked" },
    { 24, "PROG_ERROR", 
        "raised an error when running a subtask" },
    { 25, "READ_ERROR", 
        "Check the SDS file, some fields are missing" },
    { 26, "SIMULATION", 
        "Action not possible as we are in simulation mode" },
    { 27, "SLALIB", 
        "Error returned by slalib function" },
    { 28, "SEARCH", 
        "Error occured during search action" },
    { 29, "WRONG_HEIGHT", 
        "The height of Z axis is not correct" },
    {0, 0, 0 }};

static MessFacType MessFac_TDFGRIPPERTASK = 
  { 1092, "TDFGRIPPERTASK", MessFacTab_TDFGRIPPERTASK, 0 };

#endif
